### ISSUE TITLE
Issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by kishida01** [kishida01/v1_storage_deck_app#6]
■Webアプリの概要
このアプリは家庭内の消耗品の在庫管理をサポートします。
必要な消耗品の残量を把握できるようにし、視覚的にも在庫状況を確認でき、補充のタイミングを通知します。
使用イメージとして、最初にユーザーはアプリにストック情報（消耗品）を登録します。
登録内容は主にカテゴリ、商品名、想定使用人数、ストック量になります。
登録後は上記に加え、在庫切れの予定日と現在の残量が３段階で表示されます。
在庫が減ってきたらアプリが通知を送り、次回の買い物リストに自動で追加。また手動でもリスト内に追加可能です。
購入後チェックを外せばまた新たにストックとして消費のカウントを始めます。
予定日と実際の残数に齟齬がある場合は購入日から逆算し、次回以降の精度をブラッシュアップしていきます。
既存の買い物アプリでは全てを手動で行う必要があったため、常に必要なストックの入れ忘れが発生していましたが、本アプリでは持続的な在庫管理のためのサポートを可能にします。

■ProjectsのURL
https://github.com/users/kishida01/projects/1/views/1

■MVPリリースまで
- [ ] rails new
- [ ] トップページの作成
- [ ] 買い物メモ画面の作成
- [ ] ログイン機能
- [ ] ストックの登録・編集機能
- [ ] 在庫管理機能
- [ ] 通知機能
- [ ] 買い物リスト自動生成機能

■MVP後
- [ ] 消耗品の消費予測機能
- [ ] amazom、楽天アカウントとの連携
- [ ] ストック写真追加機能
- [ ] カテゴリの追加
- [ ] ページの体裁を整える

■MVPレビュー依頼予定日
予定日：2024年 9月 22日

**Comment by TakenakaEri** [comment]
issueの確認をしましたが、ストーリーポイントが見当たりませんでした。
カリキュラムをご確認いただき、ストーリーポイントを設定した状態で提出をお願いいたします。

**Comment by kishida01** [comment]
ストーリポイントをprojectに追加いたしました。
ご確認のほどよろしくお願いいたします。

**Comment by rdhdchloe** [comment]
確認できました！
LGTM！
